### ISSUE TITLE
Unicode Alt keystrokes are not working

### ISSUE THREAD

**Issue by tort32** [samclane/LIFX-Control-Panel#100]
**Describe the bug**
When running the app, Alt keystrokes for Unicode symbols stop working.

**Steps To Reproduce**
1. Run `lifx_control_panel.exe`
2. Switch to an other app with text input (example Notepad.exe)
3. Input Unicode sequence `Alt`+`0153` (holding Alt key, press numpad digits, then release Alt key)
4. Nothing appears in the text box

**Expected behavior**
Unicode "Threadmark" symbol should appears after the keystroke.

![image](https://user-images.githubusercontent.com/2276611/93635483-07220900-f9fb-11ea-970e-0ce15ecc1808.png)

**Desktop:**
 - Lifx-Control-Panel Version: 1.8.0
 - OS: Windows 10

Application is running normally, no keybinds are set by config. There is nothing particular in `lifx-control-panel.log` when reproducing the issue.

Looks like PyHook3.HookManager handling functions hinder system to process Unicode keystrokes. But I don't know this is incorrect event handling implementation or PyHook3 issue.

**Comment by samclane** [comment]
Since we switched to the `keyboard` library for keybinds, I'm wondering if this is still an issue. 

Let me see if I can reproduce on the latest version.

**Comment by tort32** [comment]
No issue with the latest release 2.1.0. Thank you 🌞
