### ISSUE TITLE
Tray Icon doesn't always disapear on close

### ISSUE THREAD

**Issue by samclane** [samclane/LIFX-Control-Panel#12]
When testing, dozens of icons pollute my tray. I don't know enough about Windows GUI and hooks to make python clean this up on exit.

**Comment by blurredpixel** [comment]
Is the tray icon through tkinter or another framework?

**Comment by samclane** [comment]
I'm using [SysTrayIcon.py](https://github.com/samclane/LIFX-Control-Panel/blob/master/SysTrayIcon.py), which uses the `win32gui` module. I don't think TK is involved in any way. I also didn't write that code, I found it in several StackOverflow questions. I used the same file in my [MinimalDiscordOverlay](https://github.com/samclane/MinimalDiscordOverlay) project, which I remember having the same problem.
