### ISSUE TITLE
Crash on startup on 2.2.1

### ISSUE THREAD

**Issue by moggrat** [samclane/LIFX-Control-Panel#132]
**Describe the bug**
Application Crashes on startup. This issue does not occur in 2.2.0

**Screenshots**

![image](https://user-images.githubusercontent.com/31907576/151885267-b1bb158f-87ee-4e6b-b0cd-f681c8241318.png)
[lifx-control-panel.log](https://github.com/samclane/LIFX-Control-Panel/files/7974745/lifx-control-panel.log)

**Desktop (please complete the following information):**
 - Lifx-Control-Panel Version: 2.2.1
 - OS: Windows 10
 - Lifx Mini

**Comment by samclane** [comment]
[Newest Release 2.2.2 should fix this](https://github.com/samclane/LIFX-Control-Panel/releases/tag/2.2.2)
