### ISSUE TITLE
"Failed to execute script - gui" on startup if old config.ini in folder

### ISSUE THREAD

**Issue by samclane** [samclane/LIFX-Control-Panel#14]
I assume it's trying to read the version number from the [Info] section, but if the old config doesn't have it then it will error. 

Will work into Issue #10

**Comment by samclane** [comment]
Haven't had this issue in a while. I think I fixed it with that [Info] fix.

**Comment by tchesket** [comment]
I randomly started getting this error message. Deleting the config file fixed it though.

**Comment by samclane** [comment]
It was most likely because I changed the keyword "all" to "full". This was because I run "eval" on the settings string, and `all` is also a reserved keyword in Python. This would cause it to evaluate `all` to be the function, rather than the string "all". Using eval statements is really dirty, but it takes so much pain out of reading settings files.
