### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Bandit** [samclane/LIFX-Control-Panel#21]
![2018-06-26_23h20_52](https://user-images.githubusercontent.com/30508/41908317-a7bf59c6-7997-11e8-81c9-e789049012ba.png)

Windows 10

**Comment by Bandit** [comment]
Worked when I ran it as administrator

**Comment by samclane** [comment]
Can you reproduce the issue and upload the `lifx-control-panel.log` file?

In the meantime, I'm uploading a bugfix that should stop this error (1.4.2).

**Comment by Bandit** [comment]
[lifx-control-panel.log](https://github.com/samclane/LIFX-Control-Panel/files/2139042/lifx-control-panel.log)

**Comment by samclane** [comment]
Yup, that confirms it. [The latest release should fix this](https://github.com/samclane/LIFX-Control-Panel/releases/tag/untagged-717aee864f2b8cab90e9). 

I'll take a look at doing lightstrip support, it's certainly on the map.
