### ISSUE TITLE
Can't bind more than one light or cannot group lights.

### ISSUE THREAD

**Issue by neurokinnetix** [samclane/LIFX-Control-Panel#23]
PC (Windows 10)

App doesn't support more than 1 light (likely a known issue) and cannot group lights to function in sync.

Adding features that can switch the lights into color cycle mode would be amazing and would be a huge plus for video game broadcasters and streamers like myself.

Please contact me if you need any donations to help further improve this project. I can't contribute very much in terms of coding but would be happy to donate a few bucks to help you keep the app updated as I do love the functionality of it even currently for the ONE light that I am able to support off of it.  

You're working is amazing Sam! Thank you for your contribution to the github community.

**Comment by samclane** [comment]
Hey neuro, thanks for the support!

When you say it "doesn't support more than one light", you're referring to grouping, correct? Because if you have multiple lights on your network, you should see them all and should be able to control them individually. If the other lights aren't showing up, that's a bug that needs to be addressed!

As for grouping, yes, I do need to implement that feature, as most people have >1 light per room and being able to change them at the same time and keep them in sync is a very important feature. However, I really didn't consider how important it was until now. I've just been considering doing a (near) complete refactor and moving to a different GUI framework before continuing development (as it would make adding new features much easier). I will see if I can squeeze grouping in to the current major version before upgrading, as it's such a requested feature.

**Comment by neurokinnetix** [comment]
Thank you for getting back to me Sam!

Yes yes both of the lights show up so no issue there... The grouping and controlling both lights using the same hot keys is where the issue is.

I tried to see if I can add both lights to use the same keys using various entries in the config file thinking that I may be able to somehow get both lights to respond to the same hot key but wasn’t able to get anything working so I thought I’d reach out to you since I loved using the control panel for our one light and was hoping there was a workaround now that we have two lights for the stream and wanted to sync them up.

Dude that would be amazing if you could manage to do squeeze that in to the final version.

I would gladly pay or donate some cheddar to you when the update drops!

Oh also, sometimes I’ve noticed that the application won’t respond when pressing the hot keys until I close it from the background and re launch it.

Not sure if it’s a sync issue in the software itself or a connection issue within the LIFX hardware but I just thought I’d pass that onto you as well in case it’s not already a known issue.

For instance, when I minimize the application into the system tray, after opening a few other games or software, the buttons will sometimes stop responding as I switch scenes in my OBS broadcasting software using the binded hot keys.

Very minor issue as it’s easy to simply close the application and relaunch it but I’m wondering if it’s something that can be patched or worked around one way or another.

Adding the color cycling features would be awesome too if you can somehow figure that one out. I noticed they don’t have the feature on the LIFX windows 10 software but have the feature on the iOS application on my iphone

________________________________

**Comment by samclane** [comment]
> Yes yes both of the lights show up so no issue there... The grouping and controlling both lights using the same hot keys is where the issue is.

Thank goodness. Not having >1 lights work was one of my biggest first bugs, and you gave me a mini heart attack when I thought it was back.

> I tried to see if I can add both lights to use the same keys using various entries in the config file thinking that I may be able to somehow get both lights to respond to the same hot key but wasn’t able to get anything working so I thought I’d reach out to you since I loved using the control panel for our one light and was hoping there was a workaround now that we have two lights for the stream and wanted to sync them up.

I can't tell you how happy it makes me that someone is getting usage out of my app. It's extra cool that you're using it while streaming. You should send me a link; I'd love to drop in and watch. 

As for the hotkeys, the way I have it currently set up is a 1-1 correspondence between the keybind and the color-changing function called. Adding another keybind to the same keycombo would just overwrite the last command. I can add "multiple actions for a single keybind" to the to-do list.  

> Oh also, sometimes I’ve noticed that the application won’t respond when pressing the hot keys until I close it from the background and re launch it.

This reeks of a run-time exception. The next time this happens, **_before_** you restart the app, could you send me the `lifx-control-panel.log` text file? That's my first step in diagnosis. Also, if you go to [releases](https://github.com/samclane/LIFX-Control-Panel/releases) and download the `LIFX-Control-Panel-debug.exe` and use that, we might be able to pinpoint the problem better. It'll run a console window in the background that spits out some verbose information about your devices, and better displays errors. There shouldn't be any sensitive info in the console, but run it and check first before using the debug-build while streaming, so you don't accidentally leak anything you don't want to.

 > Adding the color cycling features would be awesome too if you can somehow figure that one out. I noticed they don’t have the feature on the LIFX windows 10 software but have the feature on the iOS application on my iphone

Are these like the "Scenes" in the smartphone app, where the light transitions from color to color? If so, I'd certainly be interested in adding them in the future, as the goal is to try and provide a full "LIFX experience" in an open-source, desktop environment. 

However, and you'll probably agree with me here, I want to get the other features/bug fixes implemented first. Especially grouping; I think I'm turning off a lot of potential users by not having that feature (I have a single bulb, so any of the multi-bulb features are usually put in as an afterthought, unfortunately). 

Thanks again for the feedback, and I'll see what I can get working!

**Comment by neurokinnetix** [comment]
Hey Sam!

Hope you had an awesome weekend.

Sorry for getting back to you so late.

In reference to the color cycling effect, I included a screen shot showing the page on the LIFX iOS app that displays this feature.

What it does is it basically cycles through all the colors the light is capable of reproducing and allows you to set various settings such as how many degrees the color changes over the course of your desired period of time (in seconds). It’s basically a really cool “RGB” type of effect that adds some really cool ambience to the room.

[Image]

Hahahahaha and no worries man, that was my fault for not using the proper verbiage when describing the issue I was experiencing. The software itself is very solid for the most part!

Lol but ya, I was literally in the process of trying to learn how to write a script for auto-hotkey until I came across your software.... It made my life so much easier and did pretty much exactly what I needed it to do back when I only had one light running off of it.

Now that I have two lights, it would be amazing if it could support both and function the same way it did when it was just running the one light.

I’m glad it makes you proud that people are making good use out of your work Sam! It comes in very handy. If you want to stop by, you are always welcome to drop in anytime! I mainly stream battle royale and first person shooters....

Here’s my link: www.twitch.tv/kineticninja


________________________________

**Comment by neurokinnetix** [comment]
I will test it tonight for sure and will report any bugs or notes I come across after using it for a solid week or two!

________________________________

**Comment by neurokinnetix** [comment]
Hey Sam.

Ran into something that I thought might greatly help with assigning key binds.

When trying to assign key binds it does not list the group of lights as an option to assign a keybind. It only displays light one and two for example but doesn’t seem to have the option to select both when assigning hotkeys.

________________________________

**Comment by samclane** [comment]
@neurokinnetix 

I've released [1.5.0-beta.2](https://github.com/samclane/LIFX-Control-Panel/releases/tag/1.5.0-beta.2), which allows you to select a group for keybinds in the way you'd select a singular bulb. It also added my idea about only changing a single group parameter at a time, so you can, for instance, just dim all the lights in the "Dining Room" group, without changing their hue, saturation, or temp.

**Comment by samclane** [comment]
Great, thanks! 

I'll merge the patch in to the main branch and release as a stable version. Thanks for the input!

**Comment by neurokinnetix** [comment]
Another thing that would be great is if we can program a hot key to turn the lights on and off as I don’t think there is currently the option or feature to do so unless I overlooked it?

________________________________

**Comment by samclane** [comment]
You can use any color with `Brightness=0` to turn the light off. But there's no way to turn off/on while keeping previous color state. I'll try adding that.
