### ISSUE TITLE
Add in other popular/common features, like color fading and setting portions of the screen to control mutiple bulb's colors

### ISSUE THREAD

**Issue by tchesket** [samclane/LIFX-Control-Panel#32]
**Is your feature request related to a problem? Please describe.**
This app is EXTREMELY responsive compared to any others I have tried. It is great, but it can be a little jarring when watching videos etc using average screen color. 

**Describe the solution you'd like**
I absolutely love this program, and I am honestly considering learning to code python so that I can make some contributions. I would also love to see a few more features and think this program could easily become the best (by far) available for similar functions. I would literally pay someone to program in a couple more things, like being able to select different screen regions for different bulbs, allowing the colors to fade into one another slightly, and maybe a "most dominant color" instead of average color option (I'm not even sure if that last one is possible/how it works). 

**Describe alternatives you've considered**
For some reason, even though I understand this uses the lifxlan to function, I cannot seem to get many of the other utilities available to work, but this one works fine. The Lifx official app, the lifxdynamic windows 10 app, and this app all work great. But for some reason alternatives like Maxlifx and lifxlan gui on github will not find my bulbs on the lan. I cannot understand why this is.

**Does an existing product have this feature?**
I believe the Maxlifx github app allows you to set screen regions, set fade durations in ms, etc.

**Additional context**
Sorry if this is not the right place for this, I am new to github and a newbie in programming in general as well.

**Comment by samclane** [comment]
@tchesket 
Thank you so much for the positive feedback! I really love hearing from my users, even if it's just a bug report. This is definitely the right place for your feature suggestions. 

I've used MaxLifx before for research, and I've been really impressed with their Music Response features. The GUI is just amazing and really quite intuitive. Their Monitor Avg. tool has a lot more customization features than mine. **I just found out that you can't manually change the Avg. Monitor manually through the `config.ini`, as it resets to a preset and uses that internally. I'll need to change that. Each bulb having their own region would be a great change as well.** lifxlan gui, whose dev I've talked to, has great support for waveforms and preset Scenes, which I may put on the roadmap. 

**Fade-in duration for screenavg. should definitely be a user-option.** I've tried something similar to the "color crossfade" you mentioned, where I'd take the average between the current color and the newly-computed Screen Color, but all it did was cause the bulb to approach a murky skin-tone, in the same way that mixing all your fingerpaints as a kid made an ugly brown color. Your "Dominant Color" idea is also something that I've explored, and what I've found would certainly produce "quality" results. However, finding the "dominant color" is actually a machine learning problem, and all examples I saw were using a [K-Nearest-Neighbors](https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm) model, which took ~1-2 seconds to process per still image. For reference, my curent Averaging algorithm updates at ~15fps. I could try and do some optimization with Cython, but I don't know how that'll fare with my PyInstaller compiler. It would be a fun challenge at least! And if I got it to work, I know the results would be stellar. 

Thanks again for the feedback.

**Comment by tchesket** [comment]
No problem, thanks for getting back to me so quickly! I will be following this project closely and am excited for any futures updates. 

Do you happen to have any insights as to why your program has no problems discovering my lights, yet maxlifx and lifxlan gui can't seem to discover anything? I was under the impression that they worked in a similar manner to the discovery method lifx control panel uses.

As per your note about dominant colors, this makes sense. I guess that is why other programs like the lifx official app and lifxdynamic have so much lag (I was really blown away by the quickness with which your program updates, I didn't think it was possible to have such low latency).

**Comment by tchesket** [comment]
Is there any way you could upload the exe file for the new update? I can't seem to get the build process to work on my pc

**Comment by samclane** [comment]
@tchesket sure. I was just committing at a good checkpoint; it's not ready for official release yet. But I'll compile the binaries into a Beta.

**Comment by tchesket** [comment]
Awesome, I appreciate it.

**Comment by tchesket** [comment]
I just noticed another thing, you can't change the overall brightness when it is in average color mode. Would this be possible to implement? It seems like it would be fairly straightforward but I'm not sure. It would be nice to be able to either dampen the brightness of each color update or to have some kind of "maximum brightness" cap that it won't exceed. I have been watching movies/etc with this and it's awesome but it's also starting to give me a bit of a headache I think

**Comment by samclane** [comment]
@tchesket, the way the bulbs view color is a scheme called HBSK (Hue, Saturation, **Brightness**, and Kelvin). As light views color additively, the only way to achieve "blacks" is to dim the bulb. A brightness cap could still be added so that it doesn't go _above_ a certain limit.

**Comment by tchesket** [comment]
What is the new fade duration setting supposed to do? It doesn't seem to have much effect even when turned all the way up, except for delay the color changes slightly

**Comment by samclane** [comment]
It adds a "transition time" to the light changing, which also adds a delay so they don't stack up. It was partly so the user could find the value that caused the Average feature to look the smoothest.

**Comment by tchesket** [comment]
It doesn't seem to improve the flickering, if anything turning it up seems to make it worse. I'm not sure how some of the other programs, like the official lifx app, handle the color changes and makes them smoothly fade into one another, but the better response time of your program is much more impressive than the smoothness that the others provide. Maybe it's a necessary trade off, and not possible to have both smooth color transitions and very low latency

**Comment by tchesket** [comment]
I just want to add, I am very glad you are actively working on this project and responsive to feedback; I think this may be the only lifx app available that has not been abandoned. Which is pretty depressing, but at least interest in it hasn't /completely/ died out. I definitely plan on donating next time I get paid, because I appreciate your time and this is a great project.

**Comment by samclane** [comment]
@tchesket Thank you so much for the support! I originally started this project because LIFX themselves abandoned their Windows 10 app (not to mention Windows 7 users were SoL as far as desktop apps went). 

If you download an older binary release, does the flickering go away, at least with the Average function? [Let's try 1.5.4.](https://github.com/samclane/LIFX-Control-Panel/releases/tag/1.5.4)

**Comment by tchesket** [comment]
The flickering is sort of always there. It's not very bad, most of the time you can't even tell. Just sometimes when certain types of videos w/ certain colors play, you can see a bit of flickering. I think if the framerate were doubled or so (which I imagine is probably unrealistic), that would fix it. Or some of the other available programs have some sort of transition/fading method. I'm thinking of like MaxLifx for example, I don't know how that works though.
