### ISSUE TITLE
Music color feature working?

### ISSUE THREAD

**Issue by tchesket** [samclane/LIFX-Control-Panel#33]
I just noticed that the music color button does nothing, except when I am also using the average screen color effect, in which case it seems to randomly strobe white light. Is this normal/is this feature supposed to be working? I think it is likely I am just missing something, sorry if that is the case.

**Comment by samclane** [comment]
I get that on my machine too. It's because I had hardcoded the "Stereo Mix" index, and it's not always the same for every machine (and may change over time in my case). I added code to dynamically detect stereo mix index. 

As for using avg. and music at the same time, it's something I'm working towards, but that "flicker" is each thread fighting for what it thinks the "right color" is at a given instant.

**Comment by tchesket** [comment]
With the newest beta update my music color button is just grayed out. I'm assuming I'm missing something. Do I need to do something with "stereo mix"? I'm not 100% sure what is meant by that.

**Comment by samclane** [comment]
I can't find any way to do it using `pyAudio` without Stereo Mix. Essentially, it loops-back your Audio Out back In so it can be listened to like a Microphone. You can see if your sound card supports it in your Sound Recording settings.

https://www.howtogeek.com/howto/39532/how-to-enable-stereo-mix-in-windows-7-to-record-audio/

**Comment by tchesket** [comment]
I'm on windows 10, and apparently there is no stereo mix device listed in my recording settings. I tried using virtual audio cable and setting that to default, as was suggested to me when I googled it, but the music button stays grayed out, not sure how to proceed

**Comment by samclane** [comment]
I'm looking specifically for the Stereo Mix. But I can change it to let the user choose which Audio Device they want from a dropdown.

**Comment by tchesket** [comment]
That would be cool. From what I have read looking this up, it seems that they have gotten rid of the virtual stereo mix device in windows 10; it's not even listed under disabled in device manager.

**Comment by samclane** [comment]
@tchesket I added the dropdown. I also added some smoothing to the music that should fix flickering (still can't use in combo with Avg. Color).

I'm closing this issue as I think it's been addressed. If we run into more issues we'll reopen or make another thread.

**Comment by tchesket** [comment]
Okay I got the music color working now. Does it just stay on one color, and modulate the brightness based on the sound level? Or is it supposed to change colors?

**Comment by samclane** [comment]
It doesn't change colors as of yet. Ideally the next step is allowing Avg. Screen color _and_ Music Color simultaneously. Adding other color changes after that (like simple RGB Hue cycle) would be trivial.

**Comment by RunwayATR** [comment]
![Capture_LIuuuuuuuuu](https://user-images.githubusercontent.com/48583271/54488047-19485600-48f1-11e9-82be-ca05e9993fd0.jpg)
help

**Comment by samclane** [comment]
@RunwayATR could you send me your `.log` file?

**Comment by RunwayATR** [comment]
When I get home in a few hours I’ll be able to send it, sorry for making you wait

**Comment by RunwayATR** [comment]
> @RunwayATR could you send me your `.log` file?

how do i get it

**Comment by samclane** [comment]
@RunwayATR There should be a file in the same folder as the `.exe` called `lifx-control-panel.log` after running it once.
