### ISSUE TITLE
Aurora Support

### ISSUE THREAD

**Issue by JaBoiJimJam** [samclane/LIFX-Control-Panel#35]
Hi Sam, I love your program because it works well with all of my LIFX products, but I wish there was one thing, [Aurora](https://github.com/antonpup/Aurora) support. [Aurora ](https://github.com/antonpup/Aurora)is a program that allows you to sync up all your RGB peripherals regardless of their brand. It also enables you to sync up your peripherals with games like CS:GO, Rocket League, GTA 5 etc. I would love if you could add support for your program to be controlled by [Aurora](https://github.com/antonpup/Aurora).

Here is their Discord: https://discord.gg/YAuBmg9 and their website: www.project-aurora.com

**Comment by samclane** [comment]
@JaBoiJimJam I don't know very much about C# app programming, so I'm not sure what I'd need to do to expose an API to Aurora. I also believe there is a C# library for LIFX, so it may be easier just to natively build a plugin. 

Still, that's a pretty cool app and a good development effort. I'll keep an eye on it for sure.
