### ISSUE TITLE
No LIFX Devices Found

### ISSUE THREAD

**Issue by scooter2** [samclane/LIFX-Control-Panel#36]
On Windows 8.1, when starting the LIFX-Control-Panel, an error pops up saying, "No LIFX devices found on LAN. Exiting." Only option is to click "OK" and the program closes.

Currently, I have a single LIFX bulb installed and working through the official Android app on my phone. It is an "Original" bulb, if that matters.

**Comment by samclane** [comment]
Is your LIFX bulb on your Local Area Network and Subnet? 

Could you send me the local IP of your bulb and host machine?
