### ISSUE TITLE
Software interface glitches

### ISSUE THREAD

**Issue by MaestroMagnifico** [samclane/LIFX-Control-Panel#38]
When I move sliders around, this section doesn't change. https://imgur.com/a/S6C7Wma
Also after adding new shortcut, this field becomes disabled. https://imgur.com/a/zrkeqtf
I'm using Windows 10, version 1803.

**Comment by samclane** [comment]
[Fixed](https://github.com/samclane/LIFX-Control-Panel/releases/tag/1.6.2)
