### ISSUE TITLE
Brightness Smoothing

### ISSUE THREAD

**Issue by S0undfreq** [samclane/LIFX-Control-Panel#41]
I have very little knowledge on this at all but i do know when i have my asus light-strip behind my pc, that its more pinpoint on the colors. when i use the lifx app, my lifx lights seems to hop around for brightness so much that is hard to no notice the light directly. is there a way the brightness/color/ could have a smoother transition while maintaining the incredibly high reacting speed?

**Comment by samclane** [comment]
Going into "Settings" and changing "Smooth Transition Time" even to something like 0.07 will cause the light to stop flickering as much. Unfortunately, there's a trade-off between response-time and flickering. 

Let me know if this answers your question.

**Comment by S0undfreq** [comment]
yea this proved to be extremely usefull. i only realized that it was on the "to do" list after i posted it.  i appreciate the help!!
