### ISSUE TITLE
Cannot connect to LIFX strip

### ISSUE THREAD

**Issue by dnlw07** [samclane/LIFX-Control-Panel#60]
**Describe the bug**
Cannot connect to LIFX strip using **lifx_control_panel.exe**.

**To Reproduce**
1. Connect to LIFX Z 274A95
2. Run lifx_control_panel.exe
3. See error: "No LIFX devices were found on you LAN. Exiting."

**Desktop (please complete the following information):**
 - Lifx-Control-Panel Version: 1.7.5
 - Windows 10

**Please attach your logfile (lifx-control-panel.log)**
[lifx-control-panel.log](https://github.com/samclane/LIFX-Control-Panel/files/3676321/lifx-control-panel.log)

**Additional context**
I am not sure if I am doing someting wrong or not.
Networ properties:
SSID:	LIFX Z 274A95
IPv4 address:	172.16.0.2
IPv4 DNS servers:	172.16.0.1

**Comment by samclane** [comment]
Are you sure that your LIFX strip is on the same subnet as your computer?

Could you please do the following?

1. `Win`+`R` to open the `Run..` menu
2. Type `cmd` for Command Prompt
3. Type `ipconfig` and hit enter. You should get output like this:
```
Windows IP Configuration


Ethernet adapter vEthernet (DockerNAT):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::b8ab:2ba2:9e10:ce45%8
   IPv4 Address. . . . . . . . . . . : 10.0.75.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . :

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::692d:f69d:b70c:f2e0%12
   IPv4 Address. . . . . . . . . . . : 192.168.1.3
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.1.1

Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::2500:a4ee:97d9:1389%19
   IPv4 Address. . . . . . . . . . . : 192.168.136.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . :
```

Also let me know if you're using **wired** or **wireless (wifi)** internet. 

Thanks for your feedback!

**Comment by samclane** [comment]
@dnlw07 The most recent source code should be able to see LIFX "devices" in addition to "lights". If you're able to run Python directly, you could download it and see if it sees your Beam then. 

Otherwise, new Binaries (EXEs) will be coming out soon.
