### ISSUE TITLE
Error occurs during manual requirements installation

### ISSUE THREAD

**Issue by dnlw07** [samclane/LIFX-Control-Panel#61]
**Describe the bug**
While trying to execute command: **pip install lifx-control-panel** an error occurs.

**Desktop (please complete the following information):**
 - Lifx-Control-Panel Version: [Found in the "About" menu. e.g. "1.2.0"]
 - OS: [e.g. Windows 7, Windows 10, Plan 9]

**Please attach your logfile (lifx-control-panel.log)**
[error.log](https://github.com/samclane/LIFX-Control-Panel/files/3676347/error.log)

**Comment by tort32** [comment]
Looks like installer of `win32gui` is the issue: https://stackoverflow.com/questions/52806906/cant-install-win32gui
Try Python 3.6

**Comment by samclane** [comment]
`pip install pywin32` apparently works

Any luck with it @dnlw07?

**Comment by dnlw07** [comment]
hello you are right. Thank you!
