### ISSUE TITLE
[Feature Request] Add ability to select multiple home groups/accounts

### ISSUE THREAD

**Issue by prenetic** [samclane/LIFX-Control-Panel#65]
**Is your feature request related to a problem? Please describe.**
I am unable to use this application with my bulbs, since the only group of bulbs that appear in the application are from another home/account on my network.

**Describe the solution you'd like**
Preferably there would be an option to choose which home/account to use, ideally specifying a default that would be saved locally for subsequent application launches. Perhaps this would be exposed at the bottom of the screen, encapsulating the list of bulbs/groups within tabs which you can click between.

**Describe alternatives you've considered**
N/A

**Does an existing product have this feature?**
The official LIFX app on Android allows you to see your bulbs, and other bulbs on the network, although this is an authenticated scenario. The behavior would be similar however, since this app already seems aware of the home/account-to-bulb relationship.

**Additional context**
![image](https://user-images.githubusercontent.com/11982895/67822969-7f4bad00-fa7e-11e9-91c8-86ebf334b9ef.png)
Should be 18 other bulbs and various groups in this list, however I only see the one bulb from the other user's home/account on this network.

**Comment by samclane** [comment]
I believe this issue might be one of project scope. This app uses the library `lifxlan`, which only discovers lights on the Local Area Network (LAN) of the current device. 

The benefit of this is a faster communication with the lights and no login requirement from the user. The downside is that any lights _not_ on the LAN cannot be directly accessed. 

I'm sorry I can't help you here. I've been investigating issues users are having with VPNs, as those could be a possible workaround to this LAN restriction, should the user so desire.

**Comment by prenetic** [comment]
That's interesting since there are two homes on this LAN. By what you're saying, I should have seen all bulbs across both accounts, which I did not.

**Comment by mclarkk** [comment]
What does your network setup look like? Is it just a single home router with nothing special going on?
