### ISSUE TITLE
Minimum kelvin value

### ISSUE THREAD

**Issue by Raijin56** [samclane/LIFX-Control-Panel#90]
Hi, I'm using LIFX-Control-Panel version 1.7.6 in Windows 10.

The minimum kelvin value (the white color temperature) is hardcoded to 2500 K in the program. This is unfortunately incorrect because our light bulbs can reach 1500 K, and also the LIFX API specifies [here ](https://api.developer.lifx.com/docs/colors#formatting-colors) that the range it accepts is 1500-9000.

Would you be so kind to change this? It's just to modify some values in the code, specifically:
https://github.com/samclane/LIFX-Control-Panel/blob/3a45da376fe181a7c0c138bc6f5c31e66efefc7c/lifx_control_panel/__main__.pyw#L398
https://github.com/samclane/LIFX-Control-Panel/blob/3a45da376fe181a7c0c138bc6f5c31e66efefc7c/lifx_control_panel/tests/dummy_devices.py#L195
https://github.com/samclane/LIFX-Control-Panel/blob/3a45da376fe181a7c0c138bc6f5c31e66efefc7c/lifx_control_panel/tests/dummy_devices.py#L243

I'm enjoying LIFX-Control-Panel a lot, especially the Avg. Screen Color function, to make easy to the eyes to work at night.

Thank you very much and kind regards.

**Comment by samclane** [comment]
Fixed in latest push- binary coming soon.

**Comment by Raijin56** [comment]
Thank you very much @samclane ! :)
