### ISSUE TITLE
Executable is being detected as virus with Windows Defender. [Trojan:Win32/Zpevdo.B]

### ISSUE THREAD

**Issue by G-Force007** [samclane/LIFX-Control-Panel#94]
**Describe the bug**
Executable is being detected as virus with Windows Defender. [Trojan:Win32/Zpevdo.B]

**To Reproduce**
1. Windows Defender automatically detects the release executable as a virus.

**Expected behavior**
I mean, it shouldn't be detected as a virus?

**Screenshots**
![ApplicationFrameHost_EOiymehhWA](https://user-images.githubusercontent.com/2627970/89759864-6fddb200-db2e-11ea-93b9-1e80b42e6267.png)

**Desktop (please complete the following information):**
 - Lifx-Control-Panel Version: 1.8.0 from Releases page
 - OS: Windows 10 2004

![ApplicationFrameHost_T8vpgnX3jT](https://user-images.githubusercontent.com/2627970/89759996-b206f380-db2e-11ea-8185-98b2e8ebdca4.png)

**Additional context**
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Zpevdo.B!ctv&ThreatID=2147749125

**Comment by mauricio-barahona** [comment]
I'm having the exact same issue. On my PC, however, Windows will auto delete the .exe without notification.

**Comment by samclane** [comment]
Duplicated of #39
